name: Docker

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
env:
  IMAGE_NAME: xmrig

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1
      
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1
        with:
          endpoint: builders

      - name: Login to ghcr.io
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Prep Docker Tags
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1.12.0
        with:
          images: "ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}"
          tag-sha: true

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.3.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
